# http://www.appveyor.com/docs/appveyor-yml

# configuration for develop/CI and master/Release branch
-
  branches:
    only:
      - develop
      - master

  skip_tags: true
  image: Visual Studio 2017
  configuration: Release
  platform: Any CPU

  pull_requests:
    do_not_increment_build_number: false

  build_script:
    - ps: .\build.ps1 -Target Default

  artifacts:
    - path: src/bin/ControlzEx*.nupkg
    - path: src/bin/ControlzEx*.zip
