# http://www.appveyor.com/docs/appveyor-yml

branches:
  only:
    - develop
    - main
    - /\d*\.\d*\.\d*/

environment:
  azure-key-vault-url:
    secure: 1mKS/HfCVq+iYNRVSrrN8NEowOkKt3knrpMzw+SOy3g=
  azure-key-vault-client-id:
    secure: JfSqzmsJdXB6uIxttCRoQw1NygwxqXHDj9uIqQnWOb9VCnQYlRPlAnxgW0yTSX4b
  azure-key-vault-client-secret:
    secure: CUpRJxMLeUZwNPMcqI0wECaWfy5AMnWn1UZhBd9WnQ3Z16lJP1Vzrkf24mccbhUD
  azure-key-vault-certificate:
    secure: BSPdW2TgnQtoQXXbeDECug==

skip_tags: true
image: Visual Studio 2019
test: off

install:
  #- cinst dotnetcore-sdk --version=3.1.100

pull_requests:
  do_not_increment_build_number: false

build_script:
  - ps: .\build.ps1 -target CI

artifacts:
  - path: src/bin/ControlzEx*.nupkg
  - path: src/bin/ControlzEx*.zip

nuget:
  disable_publish_on_pr: true

skip_commits:
  files:
    - '**/*.md'