# http://www.appveyor.com/docs/appveyor-yml

# configuration for develop/CI and master/Release branch

branches:
  only:
    - develop
    - master

skip_tags: true
image: Visual Studio 2019 Preview
configuration: Release
platform: Any CPU

# Install dotnet core 3.0 latest (alpha!!), as this is not provided on AppVeyor yet
install:
  #- ps: Start-FileDownload 'https://dotnetcli.blob.core.windows.net/dotnet/Sdk/master/dotnet-sdk-latest-win-x64.exe'
  #- ps: Start-Process .\dotnet-sdk-latest-win-x64.exe "/install /norestart /quiet /log sdkinstall.log" -NoNewWindow -Wait
  - ps: Start-FileDownload 'https://download.visualstudio.microsoft.com/download/pr/4032ceb5-61cd-495a-ab25-475aa2232f28/7eb614e777d87ef0d49f86be4fc8bbde/dotnet-sdk-3.0.100-preview4-011223-win-x64.exe'
  - ps: Start-Process .\dotnet-sdk-3.0.100-preview4-011223-win-x64.exe "/install /norestart /quiet /log sdkinstall.log" -NoNewWindow -Wait

pull_requests:
  do_not_increment_build_number: false

build_script:
  - ps: .\build.ps1 -target CI

artifacts:
  - path: src/bin/ControlzEx*.nupkg
  - path: src/bin/ControlzEx*.zip

nuget:
  disable_publish_on_pr: true
