# http://www.appveyor.com/docs/appveyor-yml

# configuration for develop/CI branch
-
  branches:
    only:
      - develop

  environment:
    semver: 4.0.0

  image: Visual Studio 2017
  version: '%semver%-dev{build}'
  configuration: Release

  init:
    - ps: Update-AppveyorBuild -Version "$($env:appveyor_build_version.Replace("-dev$env:appveyor_build_number", "-dev"))$($env:appveyor_build_number.PadLeft(4, '0'))"
  
  # Install scripts. (runs after repo cloning)
  install:
    - nuget restore .\src\
  
  build:
    verbosity: minimal
  
  after_build:
    - cmd: nuget pack src\ControlzEx.nuspec -Version %appveyor_build_version% -Properties Configuration=%configuration%
    - ps: Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  
  assembly_info:
    patch: true
    file: src\GlobalAssemblyInfo.*
    assembly_version: "%semver%.{build}"
    assembly_file_version: "%semver%.{build}"
    assembly_informational_version: "{version}+Branch.$(APPVEYOR_REPO_BRANCH).Sha.$(APPVEYOR_REPO_COMMIT)"
  
  artifacts:
    - path: src/bin
      name: ControlzEx.$(appveyor_build_version)
      type: zip

# configuration for master/Release branch
-
  branches:
    only:
      - master

  version: 3.0.1.{build}
  configuration: Release
  
  # Install scripts. (runs after repo cloning)
  install:
    - nuget restore .\src\
  
  build:
    verbosity: minimal
  
  after_build:
    - cmd: nuget pack src\ControlzEx.nuspec -Version %appveyor_build_version% -Properties Configuration=%configuration%
    - ps: Get-ChildItem .\*.nupkg | % { Push-AppveyorArtifact $_.FullName -FileName $_.Name }
  
  assembly_info:
    patch: true
    file: src\GlobalAssemblyInfo.*
    assembly_version: "{version}"
    assembly_file_version: "{version}"
    assembly_informational_version: "{version}+Branch.$(APPVEYOR_REPO_BRANCH).Sha.$(APPVEYOR_REPO_COMMIT)"
  
  artifacts:
    - path: src/bin
      name: ControlzEx.$(appveyor_build_version)
      type: zip
